# Generated by Django 5.2.7 on 2025-10-27 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A short description of the transaction.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the transaction. Positive for expense, negative for income.', max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Dining'), ('HOUSE', 'Housing'), ('TRANS', 'Transportation'), ('ENTER', 'Entertainment'), ('OTHER', 'Other'), ('INCOME', 'Income (Deposit/Wage)')], default='OTHER', help_text='The category of the transaction.', max_length=10)),
                ('date', models.DateField(help_text='The date the transaction occurred.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the record was created.')),
                ('user', models.ForeignKey(help_text='The user who recorded this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
